### ISSUE TITLE
Let's support eslint v8

### ISSUE THREAD

**Issue by sanemat** [moneyforward/eslint-config-moneyforward#14]
We have new eslint v8!
[ESLint v8.0.0 released - ESLint - Pluggable JavaScript linter](https://eslint.org/blog/2021/10/eslint-v8.0.0-released)
[Migrating to v8.0.0 - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/migrating-to-8.0.0)

Do you have any ideas about supporting versions?

Some modules support wide range:
> "eslint": "^5.16.0 || ^6.8.0 || ^7.2.0",

https://github.com/airbnb/javascript/blob/4ee732639396362c6981b1aa4730934c3baa7919/packages/eslint-config-airbnb-base/package.json#L60

In this case, we need to have below:
>    "@typescript-eslint/eslint-plugin": "^4.28.0 || ^5.0.0",
>    "@typescript-eslint/parser": "^4.28.0 || ^5.0.0",

etc.
😅 

I prefer this way:
> "eslint": ">=7",

https://github.com/moneyforward/eslint-config-moneyforward/blob/65e0cfe97e03ec9777f85b6e9f221adce01580b1/package.json#L40

It may be fragile.

Do you have any ideas?

**Comment by kimromi** [comment]
@sanemat thank you!!

It can be fragile, but so keep the peerDependencies `"eslint": ">=7"`.
It change peerDependencies `"eslint": ">=8"` when the dependencies eslint plugins support v8.
:thinking:

- https://github.com/prettier/eslint-config-prettier/pull/201
- https://github.com/jest-community/eslint-plugin-jest/pull/903
- https://github.com/testing-library/eslint-plugin-jest-dom/pull/200
- https://github.com/mysticatea/eslint-plugin-node/pull/295
- https://github.com/yannickcr/eslint-plugin-react/pull/3059
- https://github.com/facebook/react/pull/22248
- https://github.com/testing-library/eslint-plugin-testing-library/pull/465

(I'm not good at English:pray:)
